{{- if .Values.store.tlsServer.enabled }}
{{- if not .Values.store.tlsServer.secretName }}
apiVersion: v1
data:
  tls.crt: {{ .Values.store.tlsServer.cert | b64enc }}
  tls.key: {{ .Values.store.tlsServer.key | b64enc }}
  ca.crt: {{ .Values.store.tlsServer.ca | b64enc }}
kind: Secret
metadata:
  name: {{ include "thanos.fullname" . }}-thanos-store-tls-server
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: store
type: Opaque
{{- end -}}
{{- end -}}
