{{- if semverCompare "^1.9-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ default 1 .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "traefik.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "traefik.name" . }}
        chart: {{ template "traefik.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      serviceAccountName: {{ template "traefik.fullname" . }}
      terminationGracePeriodSeconds: 60
      {{- if .Values.yaml }}
      {{- if .Values.yaml.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.yaml.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.yaml.tolerations }}
      tolerations:
{{ toYaml .Values.yaml.tolerations | indent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ template "traefik.fullname" . }}
        resources:
        {{- if .Values.yaml }}
        {{- if .Values.yaml.resources }}
{{ toYaml .Values.yaml.resources | indent 10 }}
        {{- end }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.ports.traefik.port }}
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.ports.traefik.port }}
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - name: web
          containerPort: {{ .Values.ports.web.port }}
          protocol: TCP
        - name: websecure
          containerPort: {{ .Values.ports.websecure.port }}
          protocol: TCP
        - name: traefik
          containerPort: {{ .Values.ports.traefik.port }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        {{- if .Values.accessLog.enabled }}
        - name: access-log-vol
          mountPath: {{ .Values.accessLog.volume.mountPath }}
        {{- end }}
        {{- if .Values.acme.enabled }}
        - name: acme-vol
          mountPath: /acme
        {{- end }}
        {{- if or (and .Values.acme.enabled (eq .Values.acme.challengeType "dns") .Values.acme.dnsProvider.name) .Values.env }}
        env:
        {{- range $k, $v := (index .Values.acme.dnsProvider .Values.acme.dnsProvider.name) }}
          {{- if or $v $.Values.acme.dnsProvider.existingSecretName }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
              {{- if $.Values.acme.dnsProvider.existingSecretName }}
                name: {{ $.Values.acme.dnsProvider.existingSecretName }}
              {{- else }}
                name: {{ template "traefik.fullname" $ }}-dnsprovider-config
              {{- end }}
                key: {{ $k }}
          {{- end }}
        {{- end }}
        {{- end }}
        args:
          - --configfile=/config/traefik-static.yaml
      volumes:
      - name: config
        configMap:
          name: {{ template "traefik.fullname" . }}
      {{- if .Values.accessLog.enabled }}
      - name: access-log-vol
        hostPath:
          path: {{ .Values.accessLog.volume.hostPath }}
          type: DirectoryOrCreate
      {{- end }}
      {{- if .Values.acme.enabled }}
      - name: acme-vol
      {{- if .Values.acme.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.acme.persistence.existingClaim | default (printf "%s-acme" (include "traefik.fullname" .)) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- end }}
