---
{{- if (not .Values.logs.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "traefik.fullname" . }}-logs
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.logs.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.logs.size | quote }}
  storageClassName: "{{ .Values.logs.storageClass }}"
{{- end }}
---
{{- if and .Values.fail2ban.enabled (not .Values.fail2ban.data.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "traefik.fullname" . }}-fail2ban-data
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.fail2ban.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.fail2ban.data.size | quote }}
  storageClassName: "{{ .Values.fail2ban.data.storageClass }}"
{{- end }}
---
{{- if and .Values.acme.enabled .Values.acme.persistence.enabled (not .Values.acme.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{- if .Values.acme.persistence.annotations }}
  annotations:
{{ toYaml .Values.acme.persistence.annotations | indent 4 }}
{{- end }}
  name: {{ template "traefik.fullname" . }}-acme
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.acme.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.acme.persistence.size | quote }}
  storageClassName: "{{ .Values.acme.persistence.storageClass }}"
{{- end }}
