apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: LoadBalancer
  {{- if .Values.service }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ default "Cluster" .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ template "traefik.name" . }}
    release: {{ .Release.Name }}
  ports:
  - port: 80
    name: web
    targetPort: web
  - port: 443
    name: websecure
    targetPort: websecure
